services:
  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/data/postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/data/postgres
    
    networks:
      - webapi-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=80
    ports:
      - 8080:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - webapi-network
    restart: unless-stopped
    depends_on:
      - postgres

  redis:
    image: redis
    container_name: redis_container
    command: ['redis-server', '/etc/redis/redis.conf']
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf
      - redis:/etc/redis
      - redis:/data
    networks:
      - webapi-network
    restart: unless-stopped
    ports:
      - 6379:6379

volumes:
  postgres:
  pgadmin:
  redis:
  log:

networks:
  webapi-network:
    driver: bridge